# Generated by Django 4.1 on 2024-10-31 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Luchador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('Categoria', models.CharField(max_length=100)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('altura', models.FloatField()),
                ('nacionalidad', models.CharField(max_length=50)),
                ('record', models.CharField(default='0-0-0', max_length=10)),
            ],
        ),
    ]
