# Generated by Django 4.1 on 2024-10-31 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Eva_2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='luchador',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/'),
        ),
    ]
