# Generated by Django 4.1 on 2024-10-31 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Eva_2', '0002_luchador_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='luchador',
            old_name='Categoria',
            new_name='categoria',
        ),
    ]
